llm_config:
  active_provider_id: builtin-gpt
  providers:
    - id: builtin-gpt
      provider: openai_compatible
      name: 官方默认gpt
      base_url: https://codex.ysaikeji.cn/v1
      api_key: ""
      model_name: gpt-5.4
      temperature: 0.7
      max_tokens: 8192
      vision_enabled: true
      builtin: true
    - id: builtin-claude
      provider: claude
      name: 官方默认claude
      base_url: https://api.getgoapi.com/v1
      api_key: ""
      model_name: claude-opus-4-5-20251101-thinking
      temperature: 0.7
      max_tokens: 8192
      vision_enabled: true
      builtin: true
agent_config:
  max_iterations: 100
  max_retries: 3
  max_search_results: 10
search_config:
  provider: serpapi_google
  api_key: ""
  engine: google
  gl: cn
  hl: zh-cn
mcp_config:
  mcpServers:
    amap-maps-streamableHTTP:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.amap.com/mcp?key=00b05640cc55c0ba2b7f85e0b3f2e6e7
      headers: null
    jina-mcp-server:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.jina.ai/v1
      headers:
        Authorization: Bearer jina_133c673d569840d3b1e379a526eee6d4VKMVBI9J5HYE2xd4ys7i6ehZUNb6
a2a_config:
  a2a_servers: [ ]
